---
title: "Salamander_data"
format: html
editor: visual
messages: FALSE
warnings: FALSE
---

```{r}
library(tidyverse)
library(janitor)
library(dplyr)
mack_verts <- read_csv(here("data","AS00601.csv"))

mack_verts
```

```{r}
names(mack_verts)
```

```{r}
names(mack_verts) <- tolower(names(mack_verts))
names(mack_verts)
```
```{r}
#Storing 5th values in column  "Weight" as mc_wt_5

mc_wt_5 <- mack_verts[5,15]
mc_wt_5
```
# Store the 8th - 20th value in the “LENGTH1” column as mc_length_8_20. Check by looking at your data frame to confirm.
 
```{r}
mc_length_8_20 <- mack_verts[8:20, 13]
mc_length_8_20

```

```{r}
mc_dates <- mack_verts[,17]
mc_dates
```

# Create a subset that only contains observations for Pacific Giant Salamanders (species Dicamptodon tenebrosus, stored in species as DITE). Store the subset as mc_salamanders. Hint: see dplyr::filter()!


```{r}
mc_salamaders <- mack_verts %>%
  dplyr::filter(species == "DITE")
mc_salamaders
```


```{r}

ggplot(data = mc_salamaders, aes( x = length1, y = weight)) + geom_jitter() +
  
  
```





